title: Svetlana Berezkina
description: "Описание"

author: SvetlanaBerezkina

url: "http://movetoday.ru"

baseurl: ""

theme: minima

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag
 - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

minima:

  nav_pages:
    - about.md

  show_excerpts: true

  social_links:
    - title: Telegram
      icon: telegram
      url: "https://t.me/movetoday"